# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
workflows:
  build:
    jobs:
      - build:
          context:
            - org-global
      - upload:
          context:
            - org-global
jobs:
  build:
    machine: true 
    steps:
      - checkout
      # build the application image
      - run: docker build -t tgremlin82/terraform_aws:1.0 .
  upload:
    machine: true
    steps:
      - checkout
      # login to docker hub and push the image
      - run: docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD  && docker push tgremlin82/terraform_aws:1.0
